services:
  backend-gpu:
    build:
      context: ./backend
      dockerfile: Dockerfile.gpu
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
    volumes:
      - model_cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    profiles: ["gpu"]

  backend-cpu:
    build:
      context: ./backend
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
    volumes:
      - model_cache:/root/.cache
    restart: unless-stopped
    profiles: ["cpu"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  model_cache: