FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    python3-pip ffmpeg git curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-cpu.txt requirements.txt
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

COPY . /app
WORKDIR /app

ENV PYTHONUNBUFFERED=1
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]